### ISSUE TITLE
Cust-Add Customer Insurance form has incorrect labels

### ISSUE THREAD

**Issue by naveed84n** [heartbeatservice/HeartbeatServiceSolution#10]
There are two fields that say effective date. 1 should be End Date

**Comment by naveed84n** [comment]
Assigning back to development - the label has not changed. While adding insuranc both labels still say effective date whereas one should say end date

**Comment by Raheelsid** [comment]
Not able to test - Insurance and view/edit buttons on customer seach page is not working

**Comment by Raheelsid** [comment]
![image](https://cloud.githubusercontent.com/assets/6932358/6770535/eaed3e3a-d098-11e4-9525-5869e65f5e83.png)

**Comment by Raheelsid** [comment]
There is no distinction between effective or end date on insurance form

**Comment by akhan0** [comment]
Put the label with all fields and change the date picker to kendo date picker, it will look better after design change.

**Comment by Raheelsid** [comment]
fields are now updated
