### ISSUE TITLE
Project Button

### ISSUE THREAD

**Issue by Raheelsid** [heartbeatservice/HeartbeatServiceSolution#102]
Abdullah - i think you created this project tab to test some functionality

can you please either hide this from the main portal or deploy somewhere else 

![image](https://cloud.githubusercontent.com/assets/6932358/8268862/6e9e865e-1760-11e5-9211-a9a4ead27318.png)

![image](https://cloud.githubusercontent.com/assets/6932358/8268863/7c37f156-1760-11e5-81c7-805f123d174a.png)

**Comment by akhan0** [comment]
Removed from navigation.
