### ISSUE TITLE
Ins -Customer Insurance form has incorrect values for Active field

### ISSUE THREAD

**Issue by naveed84n** [heartbeatservice/HeartbeatServiceSolution#11]
When viewing a Customer's Insurance the value for Active field is displaying false.

It should be a Yes/No field and need to confirm why is it saying false because when an insurance is added it should be added as active

**Comment by akhan0** [comment]
Active field is removed and other fields are added, all the active insurance should be displayed so there is no need to display active field in this page.

**Comment by tayyibs** [comment]
Resolved. Remaining issues with active flag are being handled on #57
