### ISSUE TITLE
Ins -Adding New Insurance from Admin menu gives browser message

### ISSUE THREAD

**Issue by naveed84n** [heartbeatservice/HeartbeatServiceSolution#15]
When you add a new insurance in Admin section and click add the message comes from the browser instead of the application

**Comment by Raheelsid** [comment]
Issue is not fixed, still receiving message from browser and clicking in on save button saved the insurance information but does not close the insurance form page.

**Comment by akhan0** [comment]
It is success message coming from browser, verify that the data is saving and insurance form is also closing.

**Comment by Raheelsid** [comment]
![image](https://cloud.githubusercontent.com/assets/6932358/6770580/be34b966-d09a-11e4-83a9-9baec1fdf5e0.png)
 Issue is now fixed
