### ISSUE TITLE
Prof -Save on Add New professional page not working

### ISSUE THREAD

**Issue by naveed84n** [heartbeatservice/HeartbeatServiceSolution#17]
If you try to add a new professional it is not working

**Comment by naveed84n** [comment]
Amir this is still not working. If you try to add a new professional and click save it is giving an error message 404. I'm assigning this back to you

**Comment by tayyibs** [comment]
Please test

**Comment by naveed84n** [comment]
This is still an issue. When you try to add a professional and click save it throws an error

**Comment by Raheelsid** [comment]
It throws a server error and does not what is missing on the form . Also the save button saves the information but does not close the form.

**Comment by akhan0** [comment]
I have deployed and verified this issue, please verify again

**Comment by akhan0** [comment]
Verified.. Please clear browser cache and verify again, it will work.

**Comment by Raheelsid** [comment]
Tested and working fine
