### ISSUE TITLE
System- Add role for the users

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#18]
Add a role for the users in the backend tables and Front end code. User can be assigned to one of the three roles

1) Super Admin
2) Admin
3) User

Once role is added  in the backend then modify the front end code to incorporate the role in the session so it is available in the UI to perform various role based activities such as Load the navigation menu based on the roles and various other features show and hide.

**Comment by umais** [comment]
This enhancment is categorized as a large enhancement and may need to be broken down in two three main enhancments

1) Update the User Table to add roles (SuperAdmin, Admin and User)
2) Need to update app so that only super admin can see the  admin menu. The admin area will be used for a lot of things but initially we need the capability to add new users , Edit Existing users . Adding Modules which will also require a new table called Modules. Modules table will already have rows inserted but in the admin area the superadmin can choose to enable and disable modules by clicking on the check box. Also Super Admin can decide which Role can see that module in the frontend. Module will basically be a dynamic menu item in the front end. for example the menu items we have today are

Dashboard(All Users Can see but will have Customized View)- 
Calendar(All Users Can see)-
Customer(all Users)-
Administration(Only Super Admin
 Projects (All User)

The additional one we would like to add is :
Modules ( A drop down menu similar to Administration that will load based on user Role)

**Comment by akhan0** [comment]
Done. Please review the functionality, added super admin, admin and user role. Added Company, Modules & User screen.

**Comment by umais** [comment]
This is now completed but there are issues open around basic functionality
