### ISSUE TITLE
Appt- Make the customer field auto complete on the schedule appointment tab.

### ISSUE THREAD

**Issue by tayyibs** [heartbeatservice/HeartbeatServiceSolution#24]
When creating a new appointment, the customer field should auto complete enabled on the appointment tab.

**Comment by umais** [comment]
The drop down that shows up on the appointment page which contains the list of customers needs to have the autocomplete feature so that users can search by typing and select the customer from a big list

**Comment by akhan0** [comment]
Please verify, it is a drop down with search functionality.

**Comment by umais** [comment]
This is now implemented
