### ISSUE TITLE
Appt- Add new page for "Appointments".

### ISSUE THREAD

**Issue by tayyibs** [heartbeatservice/HeartbeatServiceSolution#25]
Details to follow...

**Comment by tayyibs** [comment]
Need new appointment page where the we can select professional and view their appointments.

**Comment by umais** [comment]
A new Page that will show 4 drop down filters 

1)Professional Drop Down, (List of Professional, need to have autocomplete and do not load more than 100 at a given time. the User will have to Narrow down by typing)

2) Customer Drop Down,(Same as professional but will be list of customers) 

3)Start Date: Calendar showing current month view (the date should default to current date)

4)End Date: Calendar control showing current month View

Only filter 1 and 3 is required. If End Date is not provided then all appointments greater than start date for that Professional will be shown.

There will be a button with label "Show Appointments" upon clicking the button the filters should apply and show the results in a grid displaying the following information

Customer Name, Customer DOB, Customer Phone #, Customer Address, Appointment Start Time

**Comment by akhan0** [comment]
Done.

**Comment by umais** [comment]
How do I test this ?

**Comment by akhan0** [comment]
It is in Modules section and url is 
http://heartbeat-biz.com//Scheduling/Appointment/

**Comment by umais** [comment]
Okay I have tested and looks good
