### ISSUE TITLE
Ins - Unnecessary Clear button on Insurance tab

### ISSUE THREAD

**Issue by naveed84n** [heartbeatservice/HeartbeatServiceSolution#45]
When you search for a customer on the search page and then click the insurance icon there is a clear button that is not needed

**Comment by tayyibs** [comment]
Please test

**Comment by naveed84n** [comment]
i cannot test this because when i do a search on customer page and then try to click on any of the icons like view/edit, insurance nothing happens. The popups are not coming up

**Comment by akhan0** [comment]
Please verify again, application is deployed again the issue was because of workflow's page addition.

**Comment by naveed84n** [comment]
This is fixed
