### ISSUE TITLE
Build Support for Multiple Modules in our App.

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#53]
Saqib and Umais to define requirements.

**Comment by umais** [comment]
Work with issue #18 to see the roles in Timetracking

**Comment by umais** [comment]
Covered by #18

**Comment by akhan0** [comment]
Done.

**Comment by umais** [comment]
This has been completed by Arif but there are number of issues open for this. I am closing the enhancement as for the most part enhancement is already implemented.
