### ISSUE TITLE
Web Development Course - Webpage

### ISSUE THREAD

**Issue by Raheelsid** [heartbeatservice/HeartbeatServiceSolution#55]
Need to create a webpage for student to signup for the course and process payments ...we will use Paypal for credit card processing.

This is high priority item. Will start marketing next month for this course 

I will send you the requirements in email

**Comment by akhan0** [comment]
Done.

**Comment by heartbeatservice** [comment]
Not receiving email confirmation when customer register for the course .. Rest is all okay

**Comment by akhan0** [comment]
Fixed. Please send me the subject and message body, I will put it there.

**Comment by heartbeatservice** [comment]
Subject – Course Confirmation Acknowledgment
Email:
Dear Student
Thank You for registering in the web development course. It’s a three -month course and will start at 7pm on May 1st, 2015. The classes will be held at ICNA Nassau Center located at 1529 Jericho Tpke, New Hyde Park, NY 11040. There are no per-requisite for this course but basic understanding of web browsing will be required. Please bring your laptop in the class and have sufficient space in hard drive to install required software.
 Click here (Pay Now Button), if you haven’t made the payment.  Full payment is required before the start of second class.
Sincerely
The HeartBeat Team

**Comment by akhan0** [comment]
Done.

**Comment by Raheelsid** [comment]
working fine ..enhancement is fullfilled
