### ISSUE TITLE
Cust -On Add New Insurance from Customer page

### ISSUE THREAD

**Issue by naveed84n** [heartbeatservice/HeartbeatServiceSolution#59]
When adding new Insurance from the Customer Page the date fields do not have validation. Users should not be allowed to enter invalid data. the fields should calendar controls. Also, if an invalid value is provided and the user clicks save, the page throws an un-handled exception.

**Comment by akhan0** [comment]
Date control have calendar control and it is working, I have verified it from the Customer page.

**Comment by tayyibs** [comment]
This is still not working in IE

**Comment by akhan0** [comment]
Date picker control is changed from the kendo date picker, the design will look better after new design.

**Comment by Raheelsid** [comment]
Tested and working fine
