### ISSUE TITLE
Web Template

### ISSUE THREAD

**Issue by Raheelsid** [heartbeatservice/HeartbeatServiceSolution#60]
Please apply this template to our web solution 

http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/pages/index.html

**Comment by akhan0** [comment]
Implemented on Application home page and customer page, we will improve other control as well i.e., grid, date picker etc. and also on some other application pages.

**Comment by umais** [comment]
I am closing as we have opened a new issue for this already
