### ISSUE TITLE
Date field validation is expecting date time format in Chrome

### ISSUE THREAD

**Issue by tayyibs** [heartbeatservice/HeartbeatServiceSolution#61]
Date field validation is expecting date time format in Chrome.
User should be able to select date from date picker and save the record. time should not be required.

![image](https://cloud.githubusercontent.com/assets/6947022/6878682/c3cc6050-d4b8-11e4-815f-f481e9011fb8.png)

**Comment by akhan0** [comment]
The control is changed with kendo date picker, design will be modified after new design

**Comment by Raheelsid** [comment]
Tested and working fine
