### ISSUE TITLE
When editing customer insurance in Chrome, the dates to not carry.

### ISSUE THREAD

**Issue by tayyibs** [heartbeatservice/HeartbeatServiceSolution#62]
When editing customer insurance in Chrome, the previously selected date are wiped out.

![image](https://cloud.githubusercontent.com/assets/6947022/6878935/de98c4aa-d4bd-11e4-9eca-a6cf90fc08fd.png)

**Comment by akhan0** [comment]
Please veirfy

**Comment by Raheelsid** [comment]
Tested and working fine
