### ISSUE TITLE
Incorrect CustomerId getting Populated in Appointment Table

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#63]
I went to customer page and selected Naveed Aziz as the patient and then scheduled appointment. The doctor I chose from Menu was John doe but when the calendar page showed up I chose Tasneem Farooqui I scheduled an appointment and I could save it. In the backend customer Id is getting populated as 0 . Also when I go directly to the Calendar page and schedule appointment  I choose Doctor and then time slot along with Customer and in the backend the customer Is getting populated as null. 

When I come back to the caledar for that doctor and look at the details of that appointment I do not see the customer name in the drop down which tells me something is going wrong and the correct customer Id is not populating in the appointments table.

**Comment by akhan0** [comment]
Fixed and verified.

**Comment by Raheelsid** [comment]
Tested and working fine
