### ISSUE TITLE
Unable to edit existing user from Super Admin. 

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#65]
I am getting a 500 Internal Server Error when trying to Edit the User. Also one additional note. When Editing the user a super admin SHOULD NOT HAVE TO  "Reenter" the users password it should automatically be populated. The Only time super admin should enter the password is when he is resetting the password for the user.

**Comment by akhan0** [comment]
Fixed

**Comment by umais** [comment]
This is also now working but other issues have been opened around new modules and permission and roles. But this is good.
