### ISSUE TITLE
IsForAll "0" Modules should be under the menu item called Modules

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#67]
For the Modules which have a isforAll value of "0" they should be put under a menu item of "Modules".

For example if a user has the Module Calendar then when user logs in they should see "Modules" menu similar to how "Administration" menu comes up when they click on "Modules" they will see the calendar menu item and they can click on it to go to calendar module. If user has multiple modules that have isForAll value of "0" for example a user has both Calendar and BPM then when they click the Modules menu they will see two items and they can choose either one.

**Comment by akhan0** [comment]
Please check, I have created new menu "Modules" and put the customer and calendar in it.

**Comment by Raheelsid** [comment]
This looks good.
