### ISSUE TITLE
Edit User Issue and Permissions related issue (Requirement Gap)

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#68]
In the Edit User if the role selected is Super admin then all modules should automatically be selected and the checkboxes should get disabled. The reason for this is if you are a super admin then basically you have access to everything . Same thing would apply to Admin . 

The only difference between Super Admin and Admin is that an admin cannot add new companies or view or edit any other companies info except for their own. The Super Admin can add other companies and also be able to add users to other companies . When a super admin will have a drop down filer on every search page to filter by Company by default the Company which is assigned to him will be selected on every page. For every other user including admin this Company Filter would be hidden.

**Comment by akhan0** [comment]
On Super Admin & Admin role, the module list will not be available. For Super Admin, all modules are available and for Admin, all company modules are available.
For Admin, only his company is available for edit and the module list also not available for admin role. And in the user screen, company list and role list is not available.

**Comment by umais** [comment]
Looks good.
