### ISSUE TITLE
Calendar screen changes 

### ISSUE THREAD

**Issue by akhan0** [heartbeatservice/HeartbeatServiceSolution#77]
Search, Professional and customer should based on selected company.

**Comment by akhan0** [comment]
Done.

**Comment by umais** [comment]
I am having trouble testing this as I cannot schedule appointments see related bug

**Comment by akhan0** [comment]
Please verify, the UI issue of Day & Week view is still there but the functionality issue is fixed.

**Comment by umais** [comment]
looks good . Verified
