### ISSUE TITLE
Add Company name and User Role in the header section

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#81]
See image below and update the website by adding those labels in the header
![display](https://cloud.githubusercontent.com/assets/4055060/7334225/a15c322a-eb5b-11e4-8cb6-0c9e00a864e8.png)

**Comment by akhan0** [comment]
Please check, one limitation I have found that when previously selected company is not loaded in newly access page.

**Comment by umais** [comment]
Okay looks good
