### ISSUE TITLE
The Company Label in header should be set to the Current company

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#82]
Arif I like the ne dropdown and label for company on the top but when Super Admin logs in the default company should be selected based on the CompanyId assigned to the Super Admin in the UserProfile Table

**Comment by umais** [comment]
Also make the color of the company name in the header blue same as the User Name

**Comment by akhan0** [comment]
Please check.

**Comment by Raheelsid** [comment]
This is good.
