### ISSUE TITLE
The Company selected in the dropdown should  be the driver

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#83]
The Company that is selected in the dropdown when a superadmin is logged in should be the driver for all the screens in the application. Currently I am noticing that when I select say company "The Big One" and then go to the User Screen and click search it brings me all the users for Meachem Clininc . In this case I should only get Users from " The Big One" . This theme should be applicable to all the screens in the application so if I go to the customer screen or the workflow screen or the calendar screen. I should only see the view and data for the customer that appears in the header at that time. If I am on a particular screen and I change the company drop down I should be redirected to the dashboard.

**Comment by akhan0** [comment]
I already open issues (#73 to #79) for each screen, so please close this as we will manage it separately.

**Comment by Raheelsid** [comment]
So far this looks good. Just need to do some more in depth testing if any issue arises we will open a separate ticket for that.
