### ISSUE TITLE
Modules Functionality Issue

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#84]
Arif The Module assignment on the Edit User is not working correctly. Following are the issues I am facing.

1) First of all I do not see all the modules. In the List. BPM is missing from the selection.
2) Secondly if you look at the screenshot below for User JNam I assigned him three modules "Calendar", "Insurance" and Company. But When I login as him it does not show me the calendar in the modules menu but instead I see the BPM.
3) When I log back in as Super Admin and search for JNam user and clieck edit now the Modules selection is no longer selected . Something fishy is going on. 

![image](https://cloud.githubusercontent.com/assets/4055060/7339176/2d9de724-ec33-11e4-896c-d6ab46b1bb92.png)

**Comment by akhan0** [comment]
Please verify.

**Comment by umais** [comment]
Okay looks good
