### ISSUE TITLE
Module Behavior is confusing

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#85]
The only Modules that should appear in the Modules list in the checkboxes are the following

1) BPM
2) Calendar

The other modules should not appear to be selected as they are defaults . For example if it is a Super Admin or a Admin then the default modules for him are 

1) Customer, dashboard And everything under Admin

If the user that logs in and he is not a Admin or Superadmin then default modules are 

1) Customer and Dashboard.

The default modules should appear but should be disabled and selected. 

The module list should also be loaded dynamically based on the company and Role selected. I am also noticing that when I go to Customer and see which modules that company has none of them are selected but in user I can still assign these modules. This is really confusing to me. The user module list should appear based on modules that the customer has.

**Comment by akhan0** [comment]
The default module won't displayed as they will show by default. We can make the module as default in the module screen by checking "show module". 
On Super Admin & Admin role, the module list will not be available. For Super Admin, all modules are available and for Admin, all company modules are available.

**Comment by umais** [comment]
Okay Good for now
