### ISSUE TITLE
WorkFlow (BPM) Is not company driven

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#86]
I created a new user with user name samia and password is Welcome and this user belongs to the Company Big One. I only assigned the Module Calendar but I do not see the calendar in the menu instead I see BPM. when I go to BPM I can see the data that is there for other Company. It seems to be as though there is no filter based on Company in the BPM . Everything should be Driven By Company whether it is BPM , Calendar or Customers Company is the "DRIVER".

**Comment by akhan0** [comment]
This is done but previous data are not available because the previous data was without company.

**Comment by umais** [comment]
Unable to test this as I cannot save anything in category and nothing shows up I cannot create new items. Please Fix

**Comment by umais** [comment]
Arif This will be a hi priority Item

**Comment by akhan0** [comment]
Done, please check

**Comment by umais** [comment]
Okay tested and it seems to be working good now. Thanks for fixing it quickly
