### ISSUE TITLE
Customer Search not working 

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#89]
Customer Search is not working

See screnshot below. I cannot search or go to next page always get the error below.

![image](https://cloud.githubusercontent.com/assets/4055060/7339784/db9e5128-ec48-11e4-9a3f-0e4bc4a4b2d4.png)

**Comment by akhan0** [comment]
It is working, please check again..

**Comment by umais** [comment]
Tested and it works now. Thanks
