### ISSUE TITLE
Modules link not working for new user

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#91]
I logged in as a Super Admin. Selected Meachem from the customer drop down

1) Clicked on Admin and then User and then add new user. I added a new user "meachem" for the customer "meachem" the password for user "meachem" is "welcome" all lower case. I assigned meachem user all of the modules.
2) When I login with meachem account I can see that he logs in correctly and I can also see all the menu items. When I click on the Modules link I see an error page.

**Comment by akhan0** [comment]
Added scheduling home page link in Modules.

**Comment by umais** [comment]
This is still incorrect. I should see the modules that are assigned to the user "Meachem"

**Comment by akhan0** [comment]
Please verify.

**Comment by umais** [comment]
Verified
