### ISSUE TITLE
Homepage display different in IE and Chrome 

### ISSUE THREAD

**Issue by tayyibs** [heartbeatservice/HeartbeatServiceSolution#92]
IE doesn't show menu options. Unable to access modules. 

![homechrome](https://cloud.githubusercontent.com/assets/6947022/7441892/9cd6eb14-f0c9-11e4-9f29-d69b009d1738.png)
![homeie](https://cloud.githubusercontent.com/assets/6947022/7441893/9cdb21ca-f0c9-11e4-8b4d-6c2960c4ea01.png)

**Comment by akhan0** [comment]
Please verify.

**Comment by umais** [comment]
@tayyibs please verify

**Comment by Raheelsid** [comment]
IE looks fine , menu does appear on IE
