### ISSUE TITLE
Cannot save appointment even after selecting customer 

### ISSUE THREAD

**Issue by tayyibs** [heartbeatservice/HeartbeatServiceSolution#93]
I am using Chrome. I went to the calendar page and double clicked on a future date and filled in the info. I get an error saying "Please select customer" even though i have selected one already.

![appointmenterrorcust](https://cloud.githubusercontent.com/assets/6947022/7441911/a4530c28-f0ca-11e4-9103-48333075118e.png)

**Comment by akhan0** [comment]
Please verify.

**Comment by umais** [comment]
@akhan0 I opened a ticket #97 which is related as I cannot test this until that is fixed.

**Comment by akhan0** [comment]
Please verify, the UI issue of Day & Week view is still there but the functionality issue is fixed.

**Comment by umais** [comment]
Looks good
