### ISSUE TITLE
Error when saving professional

### ISSUE THREAD

**Issue by tayyibs** [heartbeatservice/HeartbeatServiceSolution#94]
Goto the Administration>>Professional and hit the search button to view all existing professionals. Now click on "Add new professional", input information and save. The record does not save and a server error is displayed. This does not happen if the search button is not pressed before saving the record.
![professionalerror](https://cloud.githubusercontent.com/assets/6947022/7441967/2f76650a-f0cd-11e4-862e-8c841a8190cc.png)

**Comment by akhan0** [comment]
Done

**Comment by umais** [comment]
Verified
