### ISSUE TITLE
Cannot Login I am getting an error see image

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#96]
![image](https://cloud.githubusercontent.com/assets/4055060/7487458/069fef50-f386-11e4-9c98-daa1a174f9d2.png)

**Comment by akhan0** [comment]
I am successfully login with user umais & tayyib, please try again if you will face again this issue try to do hard refresh.

**Comment by tayyibs** [comment]
I logged in successfully.
