### ISSUE TITLE
Unable to Create Appointment

### ISSUE THREAD

**Issue by umais** [heartbeatservice/HeartbeatServiceSolution#97]
I have refreshed my browser both in IE and Chrome. I cannot save any appointments as the appointment popup no longer shows up upon clicking a time slot. Please Fix ASAP as this is a high priority Item and is preventing us to create appointments and test multi tenancy

**Comment by akhan0** [comment]
Please verify, the UI issue of Day & Week view is still there but the functionality issue is fixed.

**Comment by umais** [comment]
Still some issues. The modal popup not always appearing .

Steps to replicate

1) Go to Customer search for a customer 
2) Use the set appointment button then choose the professional
3) Now click on a day from the month view.
4) Click on a time slot then you will see modal.
5) Close the modal without saving .
6) Then try to open another time slot and it does not show up.
7) Click on the day view
8) Now click time slot again and you will see it appear again.
9) Expected result modal should always show up even if someone closes it and then tries to open a different time slot.

**Comment by akhan0** [comment]
Fixed,

**Comment by umais** [comment]
looks good
